### ISSUE TITLE
KeywordProcessor streetnames/places causing many false positives

### ISSUE THREAD

**Issue by melvin2204** [lmeulen/PrivacyFilter#12]
In:
`Ik heb een aardbeientong`
Out:
`Ik heb <PLAATS> <AANDOENING>`
Expected:
`Ik heb een <AANDOENING>`

In:
`welke stad is dit?`
Out:
`welke <ADRES> is dit?`
Expected:
`welke stad is dit?`

**Comment by melvin2204** [comment]
Dit heeft zeker te maken met de minimum lenght van de straatnamen @lmeulen?

**Comment by lmeulen** [comment]
Is dit met of zonder NLP? Verder even checken of de lengte van minimaal 5 nog ergens wordt gehandhaafd. Dit zat in het opbouwen van de keyword processor en moet naar de dataUpdater. Als de processor is aangepast (geen controle op lengte) en het bestand bevat nog steeds alle lengtes, dan kan dit zomaar met elkaar te maken hebben.

**Comment by melvin2204** [comment]
> 
> 
> Is dit met of zonder NLP? 
Zonder

En het checken van de lengte wordt niet meer toegepast op het initaliseren omdat dat naar de data updater gaat. Ik maak er wel even een nieuwe issue voor.

**Comment by lmeulen** [comment]
Ja, ik heb de code hier staan en een update van het bestand. Zal die er dan in mergen.

**Comment by lmeulen** [comment]
What do we have to do with the names of places? E.g. 'Een' is a town but also a very common word. Multiple options

1. Keep 'Een' in the list of placenames, case-insensitive -> a lot of false replacements
2. Keep 'Een' in the list of placenames, case-sensitive -> less false replacements but names of places written without capital will not be removed. The NLP filter in the last step will replace a part of them, but not all. 'Een' at the beginning of a sentence will always be removed.
3. Only keep names of places with a minimun length in the list of placenames, case-insensitive -> a lot of false replacements
4. Filter the place names on common words and drop these from the list, trusting the NLP to remove most.

Options 3 and 4 seem the best, but especially 4 is a lot of work. I tend towards 3 for the time being

**Comment by lmeulen** [comment]
Zowel de straatnamen als de plaatsnamen hebben inmiddels een minimumlengte, afgedwongen in de DataUpdater.
Zie ook geen gekke testresultaten meer, dus ik sluit dit issue.
