### ISSUE TITLE
NLP thinks everything is a work of art

### ISSUE THREAD

**Issue by melvin2204** [lmeulen/PrivacyFilter#15]
In:
`Ik ben Melvin`
Filtered output was: 
`<WORK_OF_ART> <WORK_OF_ART> <WORK_OF_ART>`
Filtered output should have been:
`Ik ben <FILTERED>`

**Comment by lmeulen** [comment]
When I run the test in my local environment, it succeeds. After a push to Github the test fails. Is the test working on your local system?

**Comment by melvin2204** [comment]
Zullen we trouwens gewoon Nederlands praten? 😃 

> 
> 
> When I run the test in my local environment, it succeeds. After a push to Github the test fails. Is the test working on your local system?

De GH runner draait op Ubuntu 20.04 LTS en mijn systeem draait op Debian 9.13. Zou het er iets mee te maken kunnen hebben doordat ze op Linux draaien i,p.v. Windows?

**Comment by lmeulen** [comment]
Nederlands is prima, maar ik schakelde automatisch over omdat de omschrijving ('output should have been') Engels is.

Ik maak hieruit op dat de NLP test bij jou lokaal dus hetzelfde doet. Alles als work of art...

Spacy is nagenoeg volledig geschreven in Python, dan lijkt een onderliggend OS als oorzaak een kleinere kans te hebben. Ik draai, tot mijn verrassing, 2.3.7. Heb hem geinstalleerd met conda install, zou daar eigenlijk 3.0.6 verwachten maar Spacy.__version__ geeft echt 2.3.7.

**Comment by melvin2204** [comment]
Krijg jij met spacey 3.0.6 ook overal een work of art dan? 

Wat je zou kunnen doen is een nieuwe virtual enviroment maken en dan alle requirements via de requirements.txt installeren. Ik gebruik zelf Python 3.9.4
```
python --version
python -m venv venv
.\venv\Scripts\activate
python -m pip install -r requirements.txt
```

**Comment by lmeulen** [comment]
Ik zit op python 3.8.5
Het installeren obv het requirements.txt loopt bij mij vast, GDAL API version must be specified.
Dit gebeurt bij fiona>=1.8 waarna hij heel veel oudere versies gaat proberen (klinkt als jouw probleem met osm).
Krijg niet helder welk pakket uit de requirements.txt de afhankelijkheid naar fiona heeft, leek geopandas te zijn maar na het verwijderen van die afhankelijkheid blijft hij zoeken naar een versie van fiona.

Hoe heb jij toen de problemen met osmnx opgelost?

**Comment by melvin2204** [comment]
> Hoe heb jij toen de problemen met osmnx opgelost?

Ik heb het gewoon niet geinstalleerd op windows, maar op linux installeert het gewoon zonder problemen met pip. Als ik dan DataUpdater.py run loopt het overigens wel vast op "Gelderland".

**Comment by lmeulen** [comment]
Je hebt het dus opgelost door van OS te wisselen

**Comment by melvin2204** [comment]
> Je hebt het dus opgelost door van OS te wisselen

Oplossen is niet echt het juiste woord. osmnx installeert wel maar het werkt volgens mij niet.

**Comment by lmeulen** [comment]
Ik heb een nieuwe conda environment gecreerd met de afhankelijkheden, hierin wordt inderdaad alles een <workofart>, maar als ik overstap op de kleine NLP dataset (python -m spacy download nl_core_news_sm) gaat het wel goed.
Scheelt ook een hoop executietijd...
Kun jij de ..._sm ook eens poberen?

osmnx werkt bij mij prima, maar de doorlooptijd is lang. Het duurt een paar minuten om Gelderland te downloaden en de data te extraheren. Met een beetje geduld zou hij het bij jou denk ik ook doen.

**Comment by melvin2204** [comment]
Ik zit momenteel bij ATO in Amersfoort dus dat wordt op zijn vroegst morgen voordat ik dat kan proberen.

**Comment by lmeulen** [comment]
Geen probleem, maar ik vermoed dat we dan de issues hebben opgelost én een forse performance verbetering te pakken hebben.

**Comment by lmeulen** [comment]
De github action doet het ook weer :-)
