### ISSUE TITLE
Sommige achternamen zijn ook werkwoorden

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/PrivacyFilter#18]
Input : Hebben jullie het CV van Piet voor mij en Thijs?
Output: `<FILTERED>` jullie het CV van `<FILTERED>` voor mij en `<FILTERED>`?
Expected: Hebben  jullie het CV van `<FILTERED>` voor mij en `<FILTERED>`?

Voorgestelde oplossing:
Filter de lijst met voor en achternamen op werkwoorden

Mogelijke bronnen:
https://www.colanguage.com/nl/lijst-van-nederlandse-werkwoorden
https://kevinvermassen.be/Oefeningen_Nederlands/Spelling/ww-ovt/Lijst_sterke_werkwoorden.pdf
https://nl.wikipedia.org/wiki/Lijst_van_sterke_en_onregelmatige_werkwoorden_in_het_Nederlands
https://www.mijnwoordenboek.nl/werkwoorden/NL/A/1

**Comment by melvin2204** [comment]
Zou je de output van het programma tussen backticks ( \` ) kunnen zetten? Alles tussen \<haakjes\> is namelijk niet zichtbaar in GitHub.

\`Dus zoals dit.\`

**Comment by lmeulen** [comment]
Werkwoorden worden gedownload en namen, plaatsen en straatnamen worden gefilterd op deze lijst.
Nieuwe lijsten zijn ook geupload

**Comment by melvin2204** [comment]
Zou het een idee zijn om alleen werkwoorden enz eruit te filteren als er geen gebruik mag worden gemaakt van een NLP? Met een NLP zou je namelijk dat alleen kunnen toepassen op zelfstandige naamwoorden.

**Comment by lmeulen** [comment]
De filtering op verboden woorden vindt plaats voor de NLP. Als er géén gebruik mag worden gemaakt van NLP en de werkwoorden worden gefilterd, blijft de zin 'Mijn achternaam is Vossen' ongewijzigd.
Of met NLP anders opgelost kan worden, is de moeite van het proberen waard.

**Comment by melvin2204** [comment]
Ik zat hier aan te denken:

Met NLP:
1. Cleaning
2. NLP bepaalt de woordsoort
3. Bepaalde woordsoorten gaan door het statische filter case insensitive filter zonder minimum lengte.

Zonder NLP:
1. Cleaning
2. Woorden door het statische filter halen met sommige case insensitive en anderen case sensitive met minimum lengte.

Ik ben hier mee aan het experimenteren op de nlp_filter branch.

**Comment by lmeulen** [comment]
Met nieuwe implementatie filtering nieuwe status op maken.
