### ISSUE TITLE
Eén type tag in gefilterde tekst

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/PrivacyFilter#20]
Op dit moment bevat een gefilterde tekst verschillende tags, als `<NAAM>` en `<PLAATS>`.
Het voorstel is dit te veranderen in `<FILTERED>`.

De geretourneerde tags zijn soms verwarrend en kunnen tot onduidelijkheid leiden, bv `<URL>` als er een emailadres is verwijderd.

Voorstel is om dit in de laatste stap van het filter te doen, bv in de cleanup.

Voordeel is dat er geen foute tags in de tekst komen (incidenteel)
Nadeel is dat het niet duidelijk is wat er is verwijderd en dit soms handig is in de context van de tekst.

@melvin2204 Hoe denk jij hier over?

**Comment by melvin2204** [comment]
Ik denk dat dat een prima idee is. Ik doe dit ook al in de unittests om de tests makkelijker te laten slagen. De code is er al voor en kan met een regel worden opgelost.

**Comment by lmeulen** [comment]
Heb de reguliere expressie uit de test files overgenomen en in de de cleanup geplaatst. Alleen de spatie toegevoegd om alle tags te vervangen.

**Comment by melvin2204** [comment]
@lmeulen Zou je voor dit soort dingen trouwens de GH discussions feature kunnen gebruiken? Deze kan je aanzetten in de repo instellingen bij features.
