### ISSUE TITLE
URL only filtered when starting with [F|HT]TP(S)://

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/PrivacyFilter#4]
Input:
Mijn website is www.domein.nl

Output:
Mijn website is www.domein.nl

Expected:
Mijn website is <URL>

URL's are only filtered when they start with [F|HT]TP(S):// but a lot of times websites addresses are used without this prefix. When the URL starts with www. it should also be removed.

**Comment by melvin2204** [comment]
Fixed in #6
