### ISSUE TITLE
Email regex does not catch email aliasses

### ISSUE THREAD

**Issue by melvin2204** [lmeulen/PrivacyFilter#8]
Input:
`user+alias@name.tld`

Expected output:
`<EMAIL>`

Output:
`user+<EMAIL>`

**Comment by lmeulen** [comment]
Fixed in latest release, by replacing "\w" with "a-zA-Z0-9_+", this extends the \w pattern with the + sign. Note, it means multiple '+' are accepted in the mailaddress.
